### PR TITLE
Upgrade v2023.12.6

### PR DESCRIPTION
**Pull request by oufmilo**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by oufmilo** [comment]
!testme

**Comment by ScribeAwoken** [comment]
Hey, is there any way that this can get merged? v2023.12.6 was a security update, and we're at the point where it's been a month since that important security update was released upstream but it still isn't available in iceshrimp_ynh, when the upstream iceshrimp project is putting out another security update in two days.

**Comment by oufmilo** [comment]
!testme

**Comment by oufmilo** [comment]
!testme

**Comment by Salamandar** [comment]
GRnbmlf test_update_from failed obviously. Removing and restarting.

**Pull request merged**
